version: '3.7'   # Compose file format version

services:
  # Docker-in-Docker service
  dind:
    image: docker:dind
    user: root
    privileged: true
    container_name: dind
    expose:
      - 2375
    networks:
      - jenkins_dind
    environment:
      DOCKER_TLS_CERTDIR: ""

  # Jenkins service
  jenkins: {}

# Manage named volumes
volumes: {}

# Manage DinD and Jenkins communication
networks: {}

