version: '3.7'   # Compose file format version

services:
  # Docker-in-Docker service
  dind:
    image: docker:dind
    privileged: true
    container_name: dind
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client

  # Jenkins service
  jenkins: {}

# Manage named volumes
volumes: {}

# Manage DinD and Jenkins communication
networks: {}

