version: '3.7'   # Compose file format version

services:
  # Docker-in-Docker service
  dind:
    image: docker:dind
    privileged: true
    container_name: dind
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client

  # Jenkins service
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    container_name: jenkins
    depends_on:
      - dind
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
    environment:
      DOCKER_HOST: "tcp://dind:2375"
    networks:
      - jenkins_dind

# Manage named volumes
volumes: {}

# Manage DinD and Jenkins communication
networks: {}

